networks:
  fabric_network:
    driver: bridge
services:
  tls-ca:
    image: hyperledger/fabric-ca:1.5.15
    container_name: tls-ca
    ports:
    - 7054:7054
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    volumes:
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Project/fabric-ca-server-tls:/etc/hyperledger/fabric-ca-server
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Project/fabric-ca-client:/etc/hyperledger/fabric-ca-client
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Project/fabric-ca-server-tls/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
    command: sh -c 'fabric-ca-server start -badmin:adminPsw -d'
  fabric-ca-server-org1:
    image: hyperledger/fabric-ca:1.5.15
    container_name: org-ca
    ports:
    - 7055:7055
    environment:
    - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CONFIG=/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
    command: sh -c 'fabric-ca-server start -b admin:adminPsw -d'
    volumes:
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Project/fabric-ca-server-org1:/etc/hyperledger/fabric-ca-server
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Project/fabric-ca-client:/etc/hyperldger/fabric-ca-client/
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Project/fabric-ca-server-org1/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
  fabric-ca-server-int-ca:
    image: hyperledger/fabric-ca:1.5.15
    container_name: int-ca
    ports:
    - 7056:7056
    environment:
    - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CONFIG=/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
    command: sh -c 'fabric-ca-server start -b icaadmin:icaadminPsw -d'
    volumes:
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Project/fabric-ca-client/tls-ca/icaadmin:/etc/hyperledger/fabric-ca-client/icaadmin
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Project/fabric-ca-server-int-ca:/etc/hyperledger/fabric-ca-server
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Project/fabric-ca-server-int-ca/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
  orderer1.example.com:
    image: hyperledger/fabric-orderer:2.5
    container_name: orderer1.example.com
    environment:
    - FABRIC_CFG_PATH=/etc/hyperledger/fabric/config
    - FABRIC_LOGGING_SPEC=INFO
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_LISTENPORT=5050
    - ORDERER_GENERAL_CLUSTER_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_CLUSTER_LISTENPORT=7080
    - ORDERER_GENERAL_CLUSTER_TLS_ENABLED=true
    - ORDERER_GENERAL_CLUSTER_TLS_CLIENTAUTHREQUIRED=false
    - ORDERER_GENERAL_CLUSTER_SERVERCERTIFICATE=/var/hyperledger/orderer/tls/signcerts/cert.pem
    - ORDERER_GENERAL_CLUSTER_SERVERPRIVATEKEY=/var/hyperledger/orderer/tls/keystore/53a5fccc728d035c18d5513cd98f90a5f50537faac3723dde52cb054b5d9dd03_sk
    - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/signcerts/cert.pem
    - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/keystore/53a5fccc728d035c18d5513cd98f90a5f50537faac3723dde52cb054b5d9dd03_sk
    - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/tls-ca-cert.pem,
      /var/hyperledger/orderer/tls/ca-chain.pem]
    - ORDERER_GENERAL_LOCALMSPID=Consenters
    - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED=false
    - ORDERER_GENERAL_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/tls-ca-cert.pem,
      /var/hyperledger/orderer/tls/ca-chain.pem]
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/keystore/53a5fccc728d035c18d5513cd98f90a5f50537faac3723dde52cb054b5d9dd03_sk
    - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/signcerts/cert.pem
    - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/tls-ca-cert.pem,/var/hyperledger/orderer/tls/ca-chain.pem]
    - ORDERER_ADMIN_LISTENADDRESS=orderer1.example.com:9443
    - ORDERER_ADMIN_TLS_ENABLED=true
    - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/tls-ca-cert.pem, /var/hyperledger/orderer/tls/ca-chain.pem]
    - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/keystore/53a5fccc728d035c18d5513cd98f90a5f50537faac3723dde52cb054b5d9dd03_sk
    - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/signcerts/cert.pem
    - ORDERER_ADMIN_TLS_CLIENTAUTHREQUIRED=true
    - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/tls-ca-cert.pem,
      /var/hyperledger/orderer/tls/ca-chain.pem]
    - ORDERER_CHANNELPARTICIPATION_ENABLED=true
    - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis_block/sys-channel_block.pb
    - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
    - ORDERER_GENERAL_BOOTSTRAPFILE=/var/hyperledger/orderer/genesis_block/sys-channel_block.pb
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    ports:
    - 9443:9443
    - 5050:5050
    - 7080:7080
    volumes:
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Project/organizations/ordererOrganizations/Consenters/msp:/etc/hyperledger/fabric/msp
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Project/organizations/ordererOrganizations/Consenters/orderers/orderer1.example.com/msp:/var/hyperledger/orderer/msp
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Project/organizations/ordererOrganizations/Consenters/orderers/orderer1.example.com/tls:/var/hyperledger/orderer/tls
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Project/bin/:/var/hyperledger/orderer/genesis_block
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Project/orderers_bin/orderer1.example.com/config:/etc/hyperledger/fabric/config
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Project/fabric-ca-server-int-ca/ca-cert.pem:/var/hyperledger/orderer/tls/ca-cert.pem
    networks:
    - fabric_network
  peer1.peerOrg:
    container_name: peer1.peerOrg
    image: hyperledger/fabric-peer
    environment:
    - FABRIC_CFG_PATH=/etc/hyperledger/fabric/config
    - CORE_PEER_ID=peer1.peerOrg
    - CORE_PEER_ADDRESS=peer1.peerOrg:7051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
    - CORE_PEER_CHAINCODEADDRESS=peer1.peerOrg:7052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.peerOrg:7051
    - CORE_PEER_GOSSIP_INTERNALENDPOINT=peer1.peerOrg:7051
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.peerOrg:7051
    - CORE_PEER_LOCALMSPID=peerOrg
    - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:7053
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/tls-ca-cert.pem
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/signcerts/cert.pem
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/keystore/1ab6203bd4afcb54a0446876d23c255b1241dca6a0fec50677822604a1ef903d_sk
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_GOSSIP_USELEADERELECTION=true
    - CORE_PEER_GOSSIP_ORGLEADER=false
    - CORE_PEER_TLS_CLIENTKEY_FILE=/etc/hyperledger/fabric/tls/keystore/1ab6203bd4afcb54a0446876d23c255b1241dca6a0fec50677822604a1ef903d_sk
    - CORE_PEER_TLS_CLIENTCERT_FILE=/etc/hyperledger/fabric/tls/signcerts/cert.pem
    - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/fabric/tls/tlscacerts/tls-127-0-0-1-7056.pem
    - CORE_PEER_GOSSIP_ALIVEEXPIRATIONTIMEOUT=300s
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=project_fabric_network
    volumes:
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Project/peers_bin/peer1.peerOrg/config:/etc/hyperledger/fabric/config
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Project/organizations/peerOrganizations/peerOrg/users/Admin@peerOrg/msp:/etc/hyperledger/fabric/mspAdmin
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Project/organizations/peerOrganizations/peerOrg/peers/peer1.peerOrg/msp:/etc/hyperledger/fabric/msp
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Project/organizations/peerOrganizations/peerOrg/peers/peer1.peerOrg/tls:/etc/hyperledger/fabric/tls
    - /var/run/docker.sock:/var/run/docker.sock
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Project/fabric-ca-client/tls-root-cert/tls-ca-cert.pem:/etc/hyperledger/fabric/tls/tls-ca-cert.pem
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Project/fabric-ca-server-int-ca/ca-chain.pem:/etc/hyperledger/fabric/tls/ca-chain.pem
    ports:
    - 7051:7051
    - 7052:7052
    - 7053:7053
    networks:
      fabric_network:
        aliases:
        - peer1.peerOrg
    command: peer node start
  peer2.peerOrg:
    container_name: peer2.peerOrg
    image: hyperledger/fabric-peer
    environment:
    - FABRIC_CFG_PATH=/etc/hyperledger/fabric/config
    - CORE_PEER_ID=peer2.peerOrg
    - CORE_PEER_ADDRESS=peer2.peerOrg:8051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
    - CORE_PEER_CHAINCODEADDRESS=peer2.peerOrg:8052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.peerOrg:8051
    - CORE_PEER_GOSSIP_INTERNALENDPOINT=peer2.peerOrg:8051
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.peerOrg:8051
    - CORE_PEER_LOCALMSPID=peerOrg
    - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:8053
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/tls-ca-cert.pem
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/signcerts/cert.pem
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/keystore/06444f045df61996f5602669c799e957e26246c177fb563a741e034524b90eb0_sk
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_GOSSIP_USELEADERELECTION=true
    - CORE_PEER_GOSSIP_ORGLEADER=false
    - CORE_PEER_TLS_CLIENTKEY_FILE=/etc/hyperledger/fabric/tls/keystore/06444f045df61996f5602669c799e957e26246c177fb563a741e034524b90eb0_sk
    - CORE_PEER_TLS_CLIENTCERT_FILE=/etc/hyperledger/fabric/tls/signcerts/cert.pem
    - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/fabric/tls/tlscacerts/tls-127-0-0-1-7056.pem
    - CORE_PEER_GOSSIP_ALIVEEXPIRATIONTIMEOUT=300s
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=project_fabric_network
    volumes:
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Project/peers_bin/peer2.peerOrg/config:/etc/hyperledger/fabric/config
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Project/organizations/peerOrganizations/peerOrg/users/Admin@peerOrg/msp:/etc/hyperledger/fabric/mspAdmin
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Project/organizations/peerOrganizations/peerOrg/peers/peer2.peerOrg/msp:/etc/hyperledger/fabric/msp
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Project/organizations/peerOrganizations/peerOrg/peers/peer2.peerOrg/tls:/etc/hyperledger/fabric/tls
    - /var/run/docker.sock:/var/run/docker.sock
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Project/fabric-ca-client/tls-root-cert/tls-ca-cert.pem:/etc/hyperledger/fabric/tls/tls-ca-cert.pem
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/Project/fabric-ca-server-int-ca/ca-chain.pem:/etc/hyperledger/fabric/tls/ca-chain.pem
    ports:
    - 8051:8051
    - 8052:8052
    - 8053:8053
    networks:
      fabric_network:
        aliases:
        - peer2.peerOrg
    command: peer node start
