NodeOUs:
  Enable: false
  ClientOUIdentifier:
    Certificate: cacerts/127-0-0-1-7054.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/127-0-0-1-7054.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/127-0-0-1-7054.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/127-0-0-1-7054.pem
    OrganizationalUnitIdentifier: orderer
