General:
  ListenAddress: 0.0.0.0
  ListenPort: 7050
  TLS:
    Enabled: true
    PrivateKey: /var/hyperledger/orderer/tls/keystore/5662dd6d8a4497f4e52c846ec82bfcacdc2d1b666399351cf00da66e04de08ee_sk
    Certificate: /var/hyperledger/orderer/tls/signcerts/cert.pem
    RootCAs: /var/hyperledger/orderer/tls/tlscacerts/tls-127-0-0-1-7054.pem
    ClientAuthRequired: true
    ClientRootCAs:
    - /var/hyperledger/orderer/tls/tlscacerts/tls-127-0-0-1-7054.pem
  Keepalive:
    ServerMinInterval: 60s
    ServerInterval: 7200s
    ServerTimeout: 20s
  MaxRecvMsgSize: 104857600
  MaxSendMsgSize: 104857600
  Cluster:
    SendBufferSize: 100
    ClientCertificate: null
    ClientPrivateKey: null
    ListenPort: null
    ListenAddress: null
    ServerCertificate: null
    ServerPrivateKey: null
    ReplicationPolicy: null
  LocalMSPDir: /var/hyperledger/orderer/msp
  LocalMSPID: Consenters
  Profile:
    Enabled: false
    Address: 0.0.0.0:6060
  BCCSP:
    Default: SW
    SW:
      FileKeyStore:
        KeyStore: /var/hyperledger/orderer/keys
      Hash: SHA2
      Security: 256
    PKCS11:
      Library: null
      Label: null
      Pin: null
      Hash: null
      Security: null
      FileKeyStore:
        KeyStore: null
  Authentication:
    TimeWindow: 15m
FileLedger:
  Location: /var/hyperledger/production/orderer
Debug:
  BroadcastTraceDir: null
  DeliverTraceDir: null
Operations:
  ListenAddress: 127.0.0.1:8443
  TLS:
    Enabled: false
    Certificate: null
    PrivateKey: null
    ClientAuthRequired: false
    ClientRootCAs: [
      ]
Metrics:
  Provider: disabled
  Statsd:
    Network: udp
    Address: 127.0.0.1:8125
    WriteInterval: 30s
    Prefix: null
Admin:
  ListenAddress: 127.0.0.1:9443
  TLS:
    Enabled: true
    Certificate: /var/hyperledger/orderer/tls/signcerts/cert.pem
    PrivateKey: /var/hyperledger/orderer/tls/keystore/5662dd6d8a4497f4e52c846ec82bfcacdc2d1b666399351cf00da66e04de08ee_sk
    ClientAuthRequired: true
    ClientRootCAs:
    - /var/hyperledger/orderer/tls/tlscacerts/tls-127-0-0-1-7054.pem
ChannelParticipation:
  Enabled: false
  MaxRequestBodySize: 1 MB
Consensus:
  WALDir: /var/hyperledger/production/orderer/etcdraft/wal
  SnapDir: /var/hyperledger/production/orderer/etcdraft/snapshot
