Organizations:
- &id001
  Name: org1
  SkipAsForeign: false
  ID: org1
  MSPDir: /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/organizations/peerOrganizations/org1/msp
  Policies:
    Writers:
      Type: ImplicitMeta
      Rule: ANY Writers
    Admins:
      Type: ImplicitMeta
      Rule: MAJORITY Admins
    Readers:
      Type: ImplicitMeta
      Rule: ANY Readers
  OrdererEndpoints:
  - 127.0.0.1:7050
  AnchorPeers:
  - Host: 127.0.0.1
    Port: 7051
- &id002
  Policies:
    Writers:
      Type: Signature
      Rule: OR('Consenters.admin')
    Admins:
      Type: Signature
      Rule: OR('Consenters.admin')
    Readers:
      Type: Signature
      Rule: OR('Consenters.member')
  OrdererEndpoints:
  - orderer1.example.com:7080
  ID: Consenters
  Name: Consenters
  MSPDir: /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/organizations/ordererOrganizations/Consenters/msp
Capabilities:
  Channel:
    V2_0: true
  Orderer:
    V2_0: true
  Application:
    V2_0: true
Application:
  ACLs:
    _lifecycle/CheckCommitReadiness: /Channel/Application/Writers
    _lifecycle/CommitChaincodeDefinition: /Channel/Application/Writers
    _lifecycle/QueryChaincodeDefinition: /Channel/Application/Writers
    _lifecycle/QueryChaincodeDefinitions: /Channel/Application/Writers
    lscc/ChaincodeExists: /Channel/Application/Readers
    lscc/GetDeploymentSpec: /Channel/Application/Readers
    lscc/GetChaincodeData: /Channel/Application/Readers
    lscc/GetInstantiatedChaincodes: /Channel/Application/Readers
    qscc/GetChainInfo: /Channel/Application/Readers
    qscc/GetBlockByNumber: /Channel/Application/Readers
    qscc/GetBlockByHash: /Channel/Application/Readers
    qscc/GetTransactionByID: /Channel/Application/Readers
    qscc/GetBlockByTxID: /Channel/Application/Readers
    cscc/GetConfigBlock: /Channel/Application/Readers
    cscc/GetChannelConfig: /Channel/Application/Readers
    peer/Propose: /Channel/Application/Writers
    peer/ChaincodeToChaincode: /Channel/Application/Writers
    event/Block: /Channel/Application/Readers
    event/FilteredBlock: /Channel/Application/Readers
  Organizations:
  - *id001
  Policies:
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: MAJORITY Endorsement
    Endorsement:
      Type: ImplicitMeta
      Rule: MAJORITY Endorsement
    Readers:
      Type: ImplicitMeta
      Rule: ANY Readers
    Writers:
      Type: ImplicitMeta
      Rule: ANY Writers
    Admins:
      Type: ImplicitMeta
      Rule: MAJORITY Admins
  Capabilities: &id004
    V2_0: true
Orderer:
  OrdererType: solo
  Addresses: null
  BatchTimeout: 2s
  BatchSize: &id007
    MaxMessageCount: 500
    AbsoluteMaxBytes: 10 MB
    PreferredMaxBytes: 2 MB
  MaxChannels: 0
  Kafka: &id008
    Brokers:
    - kafka0:9092
    - kafka1:9092
    - kafka2:9092
  Organizations:
  - *id002
  Policies: &id009
    Readers:
      Type: ImplicitMeta
      Rule: ANY Readers
    Writers:
      Type: ImplicitMeta
      Rule: ANY Writers
    Admins:
      Type: ImplicitMeta
      Rule: MAJORITY Admins
    BlockValidation:
      Type: ImplicitMeta
      Rule: ANY Writers
  Capabilities: &id010
    V2_0: true
  addresses: &id006
  - orderer1.example.com:7080
Channel:
  Policies: &id003
    Readers:
      Type: ImplicitMeta
      Rule: ANY Readers
    Writers:
      Type: ImplicitMeta
      Rule: ANY Writers
    Admins:
      Type: ImplicitMeta
      Rule: MAJORITY Admins
  Capabilities: &id005
    V2_0: true
Profiles:
  OrdererGenesis:
    Policies: *id003
    Consortiums:
      SampleConsortium:
        Organizations:
        - *id001
    Application: &id012
      Organizations:
      - *id001
      Policies:
        Writers:
          Type: ImplicitMeta
          Rule: ANY Writers
        Admins:
          Type: ImplicitMeta
          Rule: MAJORITY Admins
        Readers:
          Type: ImplicitMeta
          Rule: ANY Readers
      Capabilities: *id004
    Capabilities: *id005
    Orderer: &id011
      OrdererType: solo
      Addresses: *id006
      BatchTimeout: 2s
      BatchSize: *id007
      MaxChannels: 0
      Kafka: *id008
      Organizations:
      - *id001
      Policies: *id009
      Capabilities: *id010
  SampleAppChannelEtcdRaft:
    Policies: *id003
    Capabilities: *id005
    Orderer: *id011
    Application: *id012
    Consortium: SampleConsortium
