networks:
  fabric_network:
    driver: bridge
services:
  ca_server:
    image: hyperledger/fabric-ca:1.5.15
    container_name: tls-ca
    ports:
    - 7054:7054
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CSR_CN=tls-ca
    - FABRIC_CA_SERVER_CA_NAME=ca-server
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server/ca-cert.pem
    - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server/msp/keystore/CA_PRIVATE_KEY
    volumes:
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/fabric-ca-server-tls/:/etc/hyperledger/fabric-ca-server
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/fabric-ca-server-tls/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
    command: sh -c 'fabric-ca-server start -badmin:adminPsw -d'
  fabric-ca-server-org1:
    image: hyperledger/fabric-ca:1.5.15
    container_name: org-ca
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=org-ca
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_CSR_CN=org-ca
    - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server/tls/cert.pem
    - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server/tls/ORG1_PRIVATE_KEY
    ports:
    - 7055:7055
    command: sh -c 'fabric-ca-server start -b admin:adminPsw -d'
    volumes:
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/fabric-ca-server-org1:/etc/hyperledger/fabric-ca-server
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/fabric-ca-server-org1/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
  orderer1.example.com:
    image: hyperledger/fabric-orderer:2.5
    container_name: orderer1.example.com
    environment:
    - FABRIC_CFG_PATH=/etc/hyperledger/fabric/config
    - FABRIC_LOGGING_SPEC=INFO
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_LISTENPORT=7050
    - ORDERER_GENERAL_CLUSTER_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_CLUSTER_LISTENPORT=7080
    - ORDERER_GENERAL_CLUSTER_TLS_ENABLED=true
    - ORDERER_GENERAL_CLUSTER_TLS_CLIENTAUTHREQUIRED=false
    - ORDERER_GENERAL_CLUSTER_SERVERCERTIFICATE=/var/hyperledger/orderer/tls/signcerts/cert.pem
    - ORDERER_GENERAL_CLUSTER_SERVERPRIVATEKEY=/var/hyperledger/orderer/tls/keystore/25cc643f034ae87d6fec32de957aa14cab96bf369a650bb7e2e08f2cdb161da2_sk
    - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tlsclient/signcerts/cert.pem
    - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tlsclient/keystore/a0ba1eb8eae7886dcd4de5373cc80d24be9197682c40353c74d8dc8174cc6bde_sk
    - ORDERER_GENERAL_CLUSTER_ROOTCAS=/var/hyperledger/orderer/tls/tls-ca-cert.pem
    - ORDERER_GENERAL_LOCALMSPID=Consenters
    - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED=false
    - ORDERER_GENERAL_TLS_CLIENTROOTCAS=/var/hyperledger/orderer/tls/tls-ca-cert.pem
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/keystore/25cc643f034ae87d6fec32de957aa14cab96bf369a650bb7e2e08f2cdb161da2_sk
    - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/signcerts/cert.pem
    - ORDERER_GENERAL_TLS_ROOTCAS=/var/hyperledger/orderer/tls/tls-ca-cert.pem
    - ORDERER_ADMIN_LISTENADDRESS=orderer1.example.com:9443
    - ORDERER_ADMIN_TLS_ENABLED=true
    - ORDERER_ADMIN_TLS_ROOTCAS=/var/hyperledger/orderer/tls/tls-ca-cert.pem
    - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/keystore/25cc643f034ae87d6fec32de957aa14cab96bf369a650bb7e2e08f2cdb161da2_sk
    - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/signcerts/cert.pem
    - ORDERER_ADMIN_TLS_CLIENTAUTHREQUIRED=true
    - ORDERER_ADMIN_TLS_CLIENTROOTCAS=/var/hyperledger/orderer/tls/tls-ca-cert.pem
    - ORDERER_CHANNELPARTICIPATION_ENABLED=true
    - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis_block/sys-channel_block.pb
    - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
    - ORDERER_GENERAL_BOOTSTRAPFILE=/var/hyperledger/orderer/genesis_block/sys-channel_block.pb
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    ports:
    - 9443:9443
    - 7050:7050
    - 7080:7080
    volumes:
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/organizations/ordererOrganizations/Consenters/msp:/etc/hyperledger/fabric/msp
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/organizations/ordererOrganizations/Consenters/orderers/orderer1.example.com/msp:/var/hyperledger/orderer/msp
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/organizations/ordererOrganizations/Consenters/orderers/orderer1.example.com/tls:/var/hyperledger/orderer/tls
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/organizations/ordererOrganizations/Consenters/orderers/orderer1.example.com/tlsclient:/var/hyperledger/orderer/tlsclient
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/bin/:/var/hyperledger/orderer/genesis_block
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/orderers_bin/orderer1.example.com/config:/etc/hyperledger/fabric/config
    networks:
    - fabric_network
  peer1.peerOrg:
    container_name: peer1.peerOrg
    image: hyperledger/fabric-peer
    environment:
    - FABRIC_CFG_PATH=/etc/hyperledger/fabric/config
    - CORE_PEER_ID=peer1.peerOrg
    - CORE_PEER_ADDRESS=peer1.peerOrg:7051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
    - CORE_PEER_CHAINCODEADDRESS=peer1.peerOrg:7052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.peerOrg:7051
    - CORE_PEER_GOSSIP_INTERNALENDPOINT=peer1.peerOrg:7051
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.peerOrg:7051
    - CORE_PEER_LOCALMSPID=peerOrg
    - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:7053
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/tls-ca-cert.pem
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/signcerts/cert.pem
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/keystore/eacd57a9139a5213a328fe559b9b8ce8821e55a8682921d2d348115a78a286ec_sk
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_GOSSIP_USELEADERELECTION=true
    - CORE_PEER_GOSSIP_ORGLEADER=false
    - CORE_PEER_TLS_CLIENTKEY_FILE=/etc/hyperledger/fabric/tls/keystore/eacd57a9139a5213a328fe559b9b8ce8821e55a8682921d2d348115a78a286ec_sk
    - CORE_PEER_TLS_CLIENTCERT_FILE=/etc/hyperledger/fabric/tls/signcerts/cert.pem
    - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/fabric/tls/tlscacerts/tls-127-0-0-1-7054.pem
    - CORE_PEER_GOSSIP_ALIVEEXPIRATIONTIMEOUT=300s
    volumes:
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/peers_bin/peer1.peerOrg/config:/etc/hyperledger/fabric/config
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/organizations/peerOrganizations/peerOrg/users/Admin@peerOrg/msp:/etc/hyperledger/fabric/mspAdmin
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/organizations/peerOrganizations/peerOrg/peers/peer1.peerOrg/msp:/etc/hyperledger/fabric/msp
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/organizations/peerOrganizations/peerOrg/peers/peer1.peerOrg/tls:/etc/hyperledger/fabric/tls
    - /var/run/docker.sock:/var/run/docker.sock
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/fabric-ca-client/tls-root-cert/tls-ca-cert.pem:/etc/hyperledger/fabric/tls/tls-ca-cert.pem
    ports:
    - 7051:7051
    - 7052:7052
    - 7053:7053
    networks:
      fabric_network:
        aliases:
        - peer1.peerOrg
    command: peer node start
  peer2.peerOrg:
    container_name: peer2.peerOrg
    image: hyperledger/fabric-peer
    environment:
    - FABRIC_CFG_PATH=/etc/hyperledger/fabric/config
    - CORE_PEER_ID=peer2.peerOrg
    - CORE_PEER_ADDRESS=peer2.peerOrg:7051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
    - CORE_PEER_CHAINCODEADDRESS=peer2.peerOrg:7052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.peerOrg:7051
    - CORE_PEER_GOSSIP_INTERNALENDPOINT=peer2.peerOrg:7051
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.peerOrg:7051
    - CORE_PEER_LOCALMSPID=peerOrg
    - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:7053
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/tls-ca-cert.pem
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/signcerts/cert.pem
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/keystore/c6858e69ebcf80f915bc910bcef90abee8c4713850fa05895b9b6dd625dded93_sk
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_GOSSIP_USELEADERELECTION=true
    - CORE_PEER_GOSSIP_ORGLEADER=false
    - CORE_PEER_TLS_CLIENTKEY_FILE=/etc/hyperledger/fabric/tls/keystore/c6858e69ebcf80f915bc910bcef90abee8c4713850fa05895b9b6dd625dded93_sk
    - CORE_PEER_TLS_CLIENTCERT_FILE=/etc/hyperledger/fabric/tls/signcerts/cert.pem
    - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/fabric/tls/tlscacerts/tls-127-0-0-1-7054.pem
    - CORE_PEER_GOSSIP_ALIVEEXPIRATIONTIMEOUT=300s
    volumes:
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/peers_bin/peer2.peerOrg/config:/etc/hyperledger/fabric/config
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/organizations/peerOrganizations/peerOrg/users/Admin@peerOrg/msp:/etc/hyperledger/fabric/mspAdmin
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/organizations/peerOrganizations/peerOrg/peers/peer2.peerOrg/msp:/etc/hyperledger/fabric/msp
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/organizations/peerOrganizations/peerOrg/peers/peer2.peerOrg/tls:/etc/hyperledger/fabric/tls
    - /var/run/docker.sock:/var/run/docker.sock
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/fabric-ca-client/tls-root-cert/tls-ca-cert.pem:/etc/hyperledger/fabric/tls/tls-ca-cert.pem
    ports:
    - 8051:7051
    - 8052:7052
    - 8053:7053
    networks:
      fabric_network:
        aliases:
        - peer2.peerOrg
    command: peer node start
