networks:
  fabric_network:
    driver: bridge
services:
  ca_server:
    image: hyperledger/fabric-ca:1.5.15
    container_name: tls-ca
    ports:
    - 7054:7054
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CSR_CN=tls-ca
    - FABRIC_CA_SERVER_CA_NAME=ca-server
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server/ca-cert.pem
    - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server/msp/keystore/CA_PRIVATE_KEY
    volumes:
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/fabric-ca-server-tls/:/etc/hyperledger/fabric-ca-server
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/fabric-ca-server-tls/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
    command: sh -c 'fabric-ca-server start -badmin:adminPsw -d'
  fabric-ca-server-org1:
    image: hyperledger/fabric-ca:1.5.15
    container_name: org-ca
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=org-ca
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_CSR_CN=org-ca
    - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server/tls/cert.pem
    - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server/tls/ORG1_PRIVATE_KEY
    ports:
    - 7055:7055
    command: sh -c 'fabric-ca-server start -b admin:adminPsw -d'
    volumes:
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/fabric-ca-server-org1:/etc/hyperledger/fabric-ca-server
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/fabric-ca-server-org1/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
  orderer1.example.com:
    image: hyperledger/fabric-orderer:2.5
    container_name: orderer1.example.com
    environment:
    - FABRIC_CFG_PATH=/etc/hyperledger/fabric/config
    - FABRIC_LOGGING_SPEC=INFO
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_LISTENPORT=7050
    - ORDERER_GENERAL_CLUSTER_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_CLUSTER_LISTENPORT=7080
    - ORDERER_GENERAL_CLUSTER_TLS_ENABLED=true
    - ORDERER_GENERAL_CLUSTER_TLS_CLIENTAUTHREQUIRED=false
    - ORDERER_GENERAL_CLUSTER_SERVERCERTIFICATE=/var/hyperledger/orderer/tls/signcerts/cert.pem
    - ORDERER_GENERAL_CLUSTER_SERVERPRIVATEKEY=/var/hyperledger/orderer/tls/keystore/c3d0e2625b486429a4c80bd79b16733fa3f5846810045b032ed0383ae3703eaf_sk
    - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tlsclient/signcerts/cert.pem
    - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tlsclient/keystore/a007d113c0667ac8b2160ec46e1e1102756b78044ea6cedecac8697749923fa9_sk
    - ORDERER_GENERAL_CLUSTER_ROOTCAS=/var/hyperledger/orderer/tls/tlscacerts/tls-127-0-0-1-7054.pem
    - ORDERER_GENERAL_LOCALMSPID=Consenters
    - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    - ORDERER_GENERAL_TLS_ENABLED=false
    - ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED=false
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/keystore/c3d0e2625b486429a4c80bd79b16733fa3f5846810045b032ed0383ae3703eaf_sk
    - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/signcerts/cert.pem
    - ORDERER_GENERAL_TLS_ROOTCAS=/var/hyperledger/orderer/tls/tlscacerts/tls-127-0-0-1-7054.pem
    - ORDERER_ADMIN_LISTENADDRESS=orderer1.example.com:9443
    - ORDERER_ADMIN_TLS_ENABLED=true
    - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/keystore/c3d0e2625b486429a4c80bd79b16733fa3f5846810045b032ed0383ae3703eaf_sk
    - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/signcerts/cert.pem
    - ORDERER_ADMIN_TLS_CLIENTAUTHREQUIRED=true
    - ORDERER_ADMIN_TLS_CLIENTROOTCAS=/var/hyperledger/orderer/tls/tlscacerts/tls-127-0-0-1-7054.pem
    - ORDERER_CHANNELPARTICIPATION_ENABLED=true
    - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis_block/sys-channel_block.pb
    - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
    - ORDERER_GENERAL_BOOTSTRAPFILE=/var/hyperledger/orderer/genesis_block/sys-channel_block.pb
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    ports:
    - 9443:9443
    - 7050:7050
    - 7080:7080
    volumes:
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/organizations/ordererOrganizations/Consenters/msp:/etc/hyperledger/fabric/msp
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/organizations/ordererOrganizations/Consenters/orderers/orderer1.example.com/msp:/var/hyperledger/orderer/msp
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/organizations/ordererOrganizations/Consenters/orderers/orderer1.example.com/tls:/var/hyperledger/orderer/tls
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/organizations/ordererOrganizations/Consenters/orderers/orderer1.example.com/tlsclient:/var/hyperledger/orderer/tlsclient
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/bin/:/var/hyperledger/orderer/genesis_block
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/orderers_bin/orderer1.example.com/config:/etc/hyperledger/fabric/config
    networks:
    - fabric_network
  peer1.peerOrg:
    container_name: peer1.peerOrg
    image: hyperledger/fabric-peer
    environment:
    - FABRIC_CFG_PATH=/etc/hyperledger/fabric/config
    - CORE_PEER_ID=peer1.peerOrg
    - CORE_PEER_ADDRESS=peer1.peerOrg:7051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
    - CORE_PEER_CHAINCODEADDRESS=peer1.peerOrg:7052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.peerOrg:7051
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.peerOrg:7051
    - CORE_PEER_LOCALMSPID=guest
    - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:7053
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/peers_bin/peer1.peerOrg/config:/etc/hyperledger/fabric/config
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/organizations/peerOrganizations/peerOrg/users/Admin@peerOrg/msp:/etc/hyperledger/fabric/msp
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/organizations/peerOrganizations/peerOrg/peers/peer1.peerOrg/tls:/etc/hyperledger/fabric/tls
    ports:
    - 7051:7051
    networks:
    - fabric_network
    command: peer node start
  peer2.peerOrg:
    container_name: peer2.peerOrg
    image: hyperledger/fabric-peer
    environment:
    - FABRIC_CFG_PATH=/etc/hyperledger/fabric/config
    - CORE_PEER_ID=peer2.peerOrg
    - CORE_PEER_ADDRESS=peer2.peerOrg:7052
    - CORE_PEER_LISTENADDRESS=0.0.0.0:7052
    - CORE_PEER_CHAINCODEADDRESS=peer2.peerOrg:7053
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7053
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.peerOrg:7052
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.peerOrg:7052
    - CORE_PEER_LOCALMSPID=guest
    - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:7054
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/peers_bin/peer2.peerOrg/config:/etc/hyperledger/fabric/config
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/organizations/peerOrganizations/peerOrg/users/Admin@peerOrg/msp:/etc/hyperledger/fabric/msp
    - /mnt/c/Users/simo0/OneDrive/Documenti/NetBeansProjects/blockchain/ProvaProject/organizations/peerOrganizations/peerOrg/peers/peer2.peerOrg/tls:/etc/hyperledger/fabric/tls
    ports:
    - 7052:7052
    networks:
    - fabric_network
    command: peer node start
